using System.Security.Cryptography;
using System.Text;

namespace RossWright;

/// <summary>
/// Cryptographic and random-generation utilities.
/// </summary>
public static class SecurityTools
{
    /// <summary>
    /// Generates a cryptographically random salt and returns both the salt and
    /// the SHA-256 hash of <paramref name="text"/> combined with that salt.
    /// </summary>
    /// <param name="text">The plain-text value to hash.</param>
    /// <returns>A tuple of <c>(salt, hash)</c> where both values are Base64 strings.</returns>
    public static (string salt, string hash) Hash(string text)
    {
        var salt = RandomString();
        byte[] textWithSaltBytes = Encoding.UTF8.GetBytes(string.Concat(text, salt));
        return (salt, Convert.ToBase64String(SHA256.HashData(textWithSaltBytes)));
    }

    /// <summary>
    /// Returns the SHA-256 hash of <paramref name="text"/> combined with
    /// <paramref name="salt"/> as a Base64 string.
    /// </summary>
    /// <param name="text">The plain-text value to hash.</param>
    /// <param name="salt">The salt previously generated by <see cref="Hash(string)"/>.</param>
    /// <returns>A Base64-encoded SHA-256 hash.</returns>
    public static string Hash(string text, string salt)
    {
        byte[] textWithSaltBytes = Encoding.UTF8.GetBytes(string.Concat(text, salt));
        return Convert.ToBase64String(SHA256.HashData(textWithSaltBytes));
    }

    /// <summary>
    /// Generates a cryptographically random Base64 string.
    /// </summary>
    /// <param name="length">The number of random bytes before Base64 encoding. Defaults to 32.</param>
    /// <returns>A Base64-encoded string of random bytes.</returns>
    public static string RandomString(int length = 32) =>
        Convert.ToBase64String(RandomNumberGenerator.GetBytes(length));

    /// <summary>
    /// Generates a string of random decimal digits.
    /// </summary>
    /// <param name="length">The number of digits to generate. Defaults to 8.</param>
    /// <returns>A string containing only digit characters.</returns>
    public static string RandomNumber(int length = 8) =>
        new string(Enumerable.Range(0, length)
            .Select(_ => (char)(RandomNumberGenerator.GetInt32(10) + '0'))
            .ToArray());
}
